<?php

namespace AppBundle\Repository;

/**
 * AddressRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AddressRepository extends \Doctrine\ORM\EntityRepository
{

    public function getAddressByUser($id)
    {
        return $this->createQueryBuilder('a')
            ->select('a')
            ->andWhere('a.user_id= :id')
            ->setParameter(':id', $id)
            ->getQuery()
            ->getOneOrNullResult();
    }
}
