<?php

namespace AppBundle\Repository;

/**
 * OptionLaundryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OptionLaundryRepository extends \Doctrine\ORM\EntityRepository
{
}
