<?php

namespace AppBundle\Repository;

/**
 * optionLaundryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class optionLaundryRepository extends \Doctrine\ORM\EntityRepository
{
}
