<?php

namespace AppBundle\Repository;

/**
 * OrderItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderItemRepository extends \Doctrine\ORM\EntityRepository
{
    public function findArray($array)
    {
        $qb = $this->createQueryBuilder('o')
            ->Select('o')
            ->Where('o.id IN (:array)')
            ->setParameter('array', $array);
        return $qb->getQuery()->getResult();
    }

    public function getOrderItemByBarcode($barcode)
    {
        return $this->createQueryBuilder('o')
            ->select('o')
            ->andWhere('o.barcode = :barcode')
            ->setParameter(':barcode', $barcode)
            ->getQuery()
            ->getOneOrNullResult();
    }
}
