<?php


namespace AppBundle\Repository;
use AppBundle\Entity\User;

/**
 * OrderLaundryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderLaundryRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param User $user
     */
    public function getListOrdersByUser(User $user)
    {
       return $this->createQueryBuilder('o')
            ->select('o')
            ->andWhere('o.user = :user')
            ->setParameter(':user',$user)
            ->getQuery()
            ->getResult();
    }
}
