<?php

namespace AppBundle\Repository;

/**
 * orderItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class orderItemRepository extends \Doctrine\ORM\EntityRepository
{
}
