<?php

namespace AppBundle\Repository;

/**
 * orderlaundryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class orderlaundryRepository extends \Doctrine\ORM\EntityRepository
{
}
