<?php

namespace AppBundle\Repository;

/**
 * TypeVetementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeVetementRepository extends \Doctrine\ORM\EntityRepository
{
}
