<?php

namespace AppBundle\Repository;

/**
 * TypeClothingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeClothingRepository extends \Doctrine\ORM\EntityRepository
{
}
