<?php

namespace AppBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    public function getUserByEmail($email)
    {
        return $this->createQueryBuilder('user', 'u')
            ->select('u')
            ->andWhere('user.email = :email')
            ->setParameter(':email', $email)
            ->getQuery()
            ->getResult();
    }
}
