# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    #service_name:
    #    class: AppBundle\Directory\ClassName
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']
    app.user_manager:
        class: AppBundle\Manager\UserManager
        arguments:
            - "@=service('doctrine').getManager()"
    app.token_authenticator:
        class:  AppBundle\Security\TokenAuthenticator
        arguments:
            - "@service_container"
    app.order_item_manager:
        class: AppBundle\Manager\OrderItemManager
        arguments:
          - "@=service('doctrine').getManager()"
    
    app.laundry_manager:
        class: AppBundle\Manager\LaundryManager
        arguments:
          - "@=service('doctrine').getManager()"

    app.cart_manager:
        class: AppBundle\Manager\CartManager
        arguments:
          - "@session"
    admin.optionlaundry:
        class: AppBundle\Admin\OptionLaundryAdmin
        arguments: [~, AppBundle\Entity\OptionLaundry, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: OptionLaundry }

    app.product_manager:
        class: AppBundle\Manager\ProductManager
        arguments:
            - "@=service('doctrine').getManager()"

